version: "3.7"

services:
  temporal-worker:
    container_name: temporal-worker
    environment:
      - NODE_ENV=development
      - POC_EMAIL_USER=${POC_EMAIL_USER}
      - POC_EMAIL_PASS=${POC_EMAIL_PASS}
      - ORCHESTRATION_TOOL=${ORCHESTRATION_TOOL}
    networks:
      - temporal-network
    build:
      context: .
      dockerfile: docker/Dockerfile-temporal-worker
    volumes:
      - ./microservices-app:/microservices-app
    depends_on:
      - express-app
