version: "3.2"
services:
  express-app:
    container_name: express-app
    hostname: express-app-host
    environment:
      - NODE_ENV=development
      - POC_EMAIL_USER=${POC_EMAIL_USER}
      - POC_EMAIL_PASS=${POC_EMAIL_PASS}
      - CONDUCTOR_HOST=localhost
      - TEMPORAL_HOST=localhost
      # - TEMPORAL_HOST=temporal-host
    networks:
      - temporal-poc-network
      - conductor-poc-network
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command:
      npm run serve
networks:
  conductor-poc-network:
    name: conductor-poc-network
    external: true
  temporal-poc-network:
    name: temporal-poc-network
    external: true
