version: "3.7"

networks:
  conductor-poc-network:
    name: conductor-poc-network

  temporal-network:
    name: temporal-network
    external: true

services:
  express-app:
    container_name: express-app
    hostname: express-app-host
    environment:
      - NODE_ENV=development
      - POC_EMAIL_USER=${POC_EMAIL_USER}
      - POC_EMAIL_PASS=${POC_EMAIL_PASS}
      - ORCHESTRATION_TOOL=${ORCHESTRATION_TOOL}
    networks:
      - temporal-network
      - conductor-poc-network
    build:
      context: .
      dockerfile: docker/Dockerfile-demo-app
    ports:
      - '4000:4000'
    expose:
      - '4000'
    volumes:
      - ./microservices-app:/microservices-app
