FROM eclipse-temurin:11-jre-focal

LABEL maintainer="DigIO"

ARG CONDUCTOR_RELEASE


RUN mkdir -p /app/config /app/logs /app/libs

# Download main Conductor server JAR
RUN curl https://repo1.maven.org/maven2/com/netflix/conductor/conductor-server/${CONDUCTOR_RELEASE}/conductor-server-${CONDUCTOR_RELEASE}-boot.jar \
    -o /app/libs/conductor-server-${CONDUCTOR_RELEASE}-boot.jar

# Download Conductor PostgreSQL persistence JAR
RUN curl https://repo1.maven.org/maven2/com/netflix/conductor/conductor-postgres-persistence/${CONDUCTOR_RELEASE}/conductor-postgres-persistence-${CONDUCTOR_RELEASE}.jar \
    -o /app/libs/conductor-postgres-persistence-${CONDUCTOR_RELEASE}.jar

RUN echo "cd /app/libs\n\n\
    java \
    -jar -DCONDUCTOR_CONFIG_FILE=/app/config/config-local.properties conductor-server-*-boot.jar \
    -cp conductor-postgres-persistence-3.13.3.jar \
    \
    2>&1 | tee -a /app/logs/server.log \
    \
    \
    " > /app/startup.sh && chmod a+x /app/startup.sh

HEALTHCHECK --interval=60s --timeout=30s --retries=10 CMD curl -I -XGET http://localhost:8080/health || exit 1

CMD [ "/app/startup.sh" ]
ENTRYPOINT [ "/bin/sh"]


