# Copyright 2023 Mantel Group Pty Ltd

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM node:14-alpine AS builder

LABEL maintainer="DigIO"

ARG CONDUCTOR_RELEASE

# Install CLI tools
RUN apk update && apk add --no-cache python3 py3-pip make g++ git

# Download latest release sources
RUN git clone https://github.com/Netflix/conductor.git && cd conductor && git checkout tags/v${CONDUCTOR_RELEASE}

WORKDIR /conductor/ui

# Build the server on run

# Installs all node packages. Cached unless package.json changes
RUN yarn install
RUN yarn build


FROM node:14-alpine
WORKDIR /app

COPY --from=builder /conductor/ui /app

CMD [ "yarn", "start" ]
