# Copyright 2023 Mantel Group Pty Ltd

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM eclipse-temurin:11-jdk-focal AS builder

LABEL maintainer="DigIO"

ARG CONDUCTOR_RELEASE

# Install CLI tools
RUN apt update && apt install -y git

# Download latest release sources
RUN git clone https://github.com/Netflix/conductor.git && cd conductor && git checkout tags/v${CONDUCTOR_RELEASE}

# Patch the server build.gradle to enabled Postgres persistence
RUN sed -i -e "s/dependencies {/dependencies {\n\truntimeOnly 'com.netflix.conductor:conductor-postgres-persistence:${CONDUCTOR_RELEASE}'/"\
    /conductor/server/build.gradle

WORKDIR /conductor

# Build the server on run
RUN ./gradlew build -x test --stacktrace

### The following is as in the original Conductor sources

# ===========================================================================================================
# 1. Bin stage
# ===========================================================================================================
FROM eclipse-temurin:11-jre-focal

LABEL maintainer="Netflix OSS <conductor@netflix.com>"

# Make app folders
RUN mkdir -p /app/config /app/logs /app/libs

# Copy the compiled output to new image
COPY --from=builder /conductor/docker/server/bin /app
COPY --from=builder /conductor/docker/server/config /app/config
COPY --from=builder /conductor/server/build/libs/conductor-server-*-boot.jar /app/libs

# Copy the files for the server into the app folders
RUN chmod +x /app/startup.sh

HEALTHCHECK --interval=60s --timeout=30s --retries=10 CMD curl -I -XGET http://localhost:8080/health || exit 1

CMD [ "/app/startup.sh" ]
ENTRYPOINT [ "/bin/sh"]
